### ISSUE TITLE
Good way to test the output of entire lib

### ISSUE THREAD

**Issue by chrisopedia** [oddbird/true#112]
I was wondering if there would be a good way to write a test using True that would test the entire output/compiled CSS file?

**Comment by mirisuzanne** [comment]
Well, what exactly is the test? If the test is "fail if this file changes" – you can just use version diffs in git. Normally, I would use True to test internal logic of mixins and functions, rather than the actual style of a site. You could write a large assertion with the entire file copy-pasted into `input`, and the results pasted into `expect`, but I'm not sure it's very useful. Maybe some form of visual regression testing instead? What problem are you trying to solve?

**Comment by chrisopedia** [comment]
Yeah, I agree that git is probably better suited for this and almost certainly visual regression.  However, I don't check in the compiled files and use enterprise NPM to host and compile. I also architect my SCSS so everything is a mixin since its used as a dependency in my entire company consumes the lib I've built into their application.  The mixin itself is configurable so they can use various parts of the lib without having to take the whole thing.  So I want to test the mixin that outputs the various ways they're using it, so I can insure there aren't unexpected results.

**Comment by mirisuzanne** [comment]
ok, you can absolutely test the output of mixins – though it's only automated if you are using the Mocha integration (or integrating with another JS test-runner). Sass isn't able to compare output internally. See the [Comparing Output](http://oddbird.net/true/api-assert-output.html) section of the docs…

```scss
@include assert {
  @include output {
    @include your-mixin-here;
  }
  @include expect {
    /* expected CSS output here */
  }
}
```

**Comment by chrisopedia** [comment]
When I do something like that, I keep getting this error:

```
Message:
    Command failed: mocha /Users/chrisopedia/Code/frontendgine/legion/styles/tests/sass-true.js --colors --reporter=mochawesome --reporter-options=reportDir=reports/sass-true,reportFilename=sass-true
/Users/chrisopedia/Code/frontendgine/legion/styles/node_modules/sass-true/lib/main.js:124
    throw parseError('Unexpected rule type "' + rule.type + '"', 'module header', rule.position);
    ^

Error: Line 2, column 1: Unexpected rule type "rule"; looking for module header.
-- Context --
@charset "UTF-8";
html {
^

    at parseError (/Users/chrisopedia/Code/frontendgine/legion/styles/node_modules/sass-true/lib/main.js:93:12)
    at parseModule (/Users/chrisopedia/Code/frontendgine/legion/styles/node_modules/sass-true/lib/main.js:124:11)
    at /Users/chrisopedia/Code/frontendgine/legion/styles/node_modules/sass-true/lib/main.js:83:17
    at Function._.each._.forEach (/Users/chrisopedia/Code/frontendgine/legion/styles/node_modules/underscore/underscore.js:153:9)
    at parseCss (/Users/chrisopedia/Code/frontendgine/legion/styles/node_modules/sass-true/lib/main.js:82:7)
    at module.exports.parse (/Users/chrisopedia/Code/frontendgine/legion/styles/node_modules/sass-true/lib/main.js:289:10)
    at Object.module.exports.runSass (/Users/chrisopedia/Code/frontendgine/legion/styles/node_modules/sass-true/lib/main.js:35:17)
    at glob.sync.forEach (/Users/chrisopedia/Code/frontendgine/legion/styles/tests/sass-true.js:10:14)
    at Array.forEach (native)
    at Object.<anonymous> (/Users/chrisopedia/Code/frontendgine/legion/styles/tests/sass-true.js:9:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /Users/chrisopedia/Code/frontendgine/legion/styles/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/chrisopedia/Code/frontendgine/legion/styles/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/Users/chrisopedia/Code/frontendgine/legion/styles/node_modules/mocha/lib/mocha.js:495:10)
    at Object.<anonymous> (/Users/chrisopedia/Code/frontendgine/legion/styles/node_modules/mocha/bin/_mocha:469:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3```

**Comment by mirisuzanne** [comment]
I think that's fixed in the [latest beta release](https://github.com/oddbird/true/releases/tag/v3.0.0-beta.1) (which is probably ready for a full release). Older versions of the parser would break on unexpected output (anything not inside a test).

**Comment by chrisopedia** [comment]
k.  I can wait for that then, thanks so much.
