### ISSUE TITLE
includePaths with runSass

### ISSUE THREAD

**Issue by chrisopedia** [oddbird/true#130]
Is it possible to use `includePaths` with `runSass({file})` or must you use the `data` option of node-sass?  When I added with the `file`, it appeared to choke on the file and no longer reading it?  Below is what I'm using now with `data` but it seems to choke on relative paths in the test file.

```js
use strict;

/* global describe it */
/* eslint no-undef: "error" */
const fs = require('fs');
const glob = require('glob');
const sassTrue = require('sass-true');

const readFile = path => new Promise((resolve, reject) => {
     fs.readFile(path, 'utf8', (err, data) => {
         if (err) {
             return reject(err);
         }
         resolve(data);
     })
});

// Run tests
glob.sync('**/__tests__/_*.scss').forEach(file =>
    readFile(file).then(data => {
        sassTrue.runSass({
            data,
            includePaths: [
                'node_modules',
                'node_modules/@user'
            ]
        }, describe, it)
    })
);
```

I get errors like the following:

```node
(node:38615) UnhandledPromiseRejectionWarning: Error: undefined:4166:578: property missing ':'
    at error (/styles/node_modules/css/lib/parse/index.js:62:15)
    at declaration (/styles/node_modules/css/lib/parse/index.js:224:33)
    at declarations (/styles/node_modules/css/lib/parse/index.js:253:19)
    at rule (/styles/node_modules/css/lib/parse/index.js:561:21)
    at rules (/styles/node_modules/css/lib/parse/index.js:118:70)
    at stylesheet (/styles/node_modules/css/lib/parse/index.js:81:21)
    at Object.module.exports [as parse] (/styles/node_modules/css/lib/parse/index.js:565:20)
    at parseCss (/styles/node_modules/sass-true/lib/main.js:91:19)
    at module.exports.parse (/styles/node_modules/sass-true/lib/main.js:332:10)
    at Object.module.exports.runSass (/styles/node_modules/sass-true/lib/main.js:40:17)
    at readFile.then.data (/styles/node_modules/@rubicon/true-config/index.js:21:18)
    at <anonymous>
(node:38615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:38615) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by jgerigmeyer** [comment]
@chrisopedia Yes, you can use `includePaths` along with the `file` option when calling `runSass`. True simply passes the options directly along to node-sass' `renderSync` function, with the only modification being adding True itself to the `includePaths` array.

If you push a stripped-down repo with the error, I'm happy to take a quick look to see where the error might be coming from.

**Comment by chrisopedia** [comment]
@jgerigmeyer its a private repo from within my companies Github Enterprise.  I can push it to a private repo fully contained within Bitbucket if you have an account there.

**Comment by jgerigmeyer** [comment]
It'd probably be more useful to create a new bare-bones repo specifically with the goal of isolating the bug/error. So just with the basics required to replicate what you're trying to do in the larger repo.

**Comment by chrisopedia** [comment]
it appears it has to do with this line:

```scss
background-image: $input-loading-icon;
```

which ends up resolving to:

```scss
$input-loading-icon: str-replace(url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='200' height='200' preserveAspectRatio='xMidYMid' viewBox='0 0 100 100'%3E%3Crect width='12' height='12' x='44' y='24' fill='%239eacb1' rx='35.2' ry='19.2'%3E%3Canimate attributeName='opacity' begin='-0.875s' dur='1s' keyTimes='0;1' repeatCount='indefinite' values='1;0'/%3E%3C/rect%3E%3Crect width='12' height='12' x='44' y='24' fill='%239eacb1' rx='35.2' ry='19.2' transform='rotate(45 50 50)'%3E%3Canimate attributeName='opacity' begin='-0.75s' dur='1s' keyTimes='0;1' repeatCount='indefinite' values='1;0'/%3E%3C/rect%3E%3Crect width='12' height='12' x='44' y='24' fill='%239eacb1' rx='35.2' ry='19.2' transform='rotate(90 50 50)'%3E%3Canimate attributeName='opacity' begin='-0.625s' dur='1s' keyTimes='0;1' repeatCount='indefinite' values='1;0'/%3E%3C/rect%3E%3Crect width='12' height='12' x='44' y='24' fill='%239eacb1' rx='35.2' ry='19.2' transform='rotate(135 50 50)'%3E%3Canimate attributeName='opacity' begin='-0.5s' dur='1s' keyTimes='0;1' repeatCount='indefinite' values='1;0'/%3E%3C/rect%3E%3Crect width='12' height='12' x='44' y='24' fill='%239eacb1' rx='35.2' ry='19.2' transform='rotate(180 50 50)'%3E%3Canimate attributeName='opacity' begin='-0.375s' dur='1s' keyTimes='0;1' repeatCount='indefinite' values='1;0'/%3E%3C/rect%3E%3Crect width='12' height='12' x='44' y='24' fill='%239eacb1' rx='35.2' ry='19.2' transform='rotate(225 50 50)'%3E%3Canimate attributeName='opacity' begin='-0.25s' dur='1s' keyTimes='0;1' repeatCount='indefinite' values='1;0'/%3E%3C/rect%3E%3Crect width='12' height='12' x='44' y='24' fill='%239eacb1' rx='35.2' ry='19.2' transform='rotate(270 50 50)'%3E%3Canimate attributeName='opacity' begin='-0.125s' dur='1s' keyTimes='0;1' repeatCount='indefinite' values='1;0'/%3E%3C/rect%3E%3Crect width='12' height='12' x='44' y='24' fill='%239eacb1' rx='35.2' ry='19.2' transform='rotate(315 50 50)'%3E%3Canimate attributeName='opacity' begin='0s' dur='1s' keyTimes='0;1' repeatCount='indefinite' values='1;0'/%3E%3C/rect%3E%3C/svg%3E"), "#", "%23");
```

**Comment by chrisopedia** [comment]
It appears to be an issue with `css` lib when parsing the `;` character that exists in the variable definition.  I set up the reduced test case at the following URL and when i replaced the `;` with `%3B` it seems to work just fine.

https://runkit.com/chrisopedia/css-parse-reduced-test-case

**Comment by jgerigmeyer** [comment]
Closing as unrelated to True (correct me if I'm wrong).
