### ISSUE TITLE
Reference Error: `describe` is not defined

### ISSUE THREAD

**Issue by chrisopedia** [oddbird/true#132]
Hey team, love what you're doing here and I've found this repo absolutely necessary in my workflow.  I was working on changing from `mocha` to `jest` since I use it for my JS testing and would love to clean up my build process to only use the 1.  My current setup works with Gulp and Mocha, but here's my newest version:

```js
// sasstrue.setup.js
'use strict';

const { sync } = require('glob');
const { runSass } = require('sass-true');

const files = sync('**/__tests__/*.scss');
const includePaths = [
    'node_modules',
];


describe('SCSS', () => {
    // Run tests
    files.forEach(file => runSass({ file, includePaths }, describe, it));
})
```

```js
// gulpfile
'use strict';

const { existsSync, mkdirSync } = require('fs');
const PluginError = require('plugin-error');
const jest = require('jest-cli');
const sasstrue = require('sasstrue.setup');

const config = {
        json: true,
        outputFile: 'scss-report.json'
};

gulp.task('test:css', done => jest.runCLI(config, [sasstrue], results => {
        if (results.numFailedTests || results.numFailedTestSuites) {
            const error = new PluginError('jest-cli', { message: 'Failed at least 1 test' });
            return done(error);
        }
        return done();
}));

gulp.task('test:css').description = 'Sass unit tests. <http://oddbird.net/true/>';
```

Full Stack Trace:

```sh
[14:37:14] ReferenceError: describe is not defined
    at Object.<anonymous> (/styles/node_modules/@rubicon/true-config/index.js:13:1)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (/styles/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at exports.default.configPath (/styles/node_modules/jest-config/build/read_config_file_and_set_root_dir.js:42:20)
    at readConfig (/styles/node_modules/jest-config/build/index.js:116:112)
    at getConfigs (/styles/node_modules/jest-cli/build/cli/index.js:314:77)
    at Object.<anonymous> (/styles/node_modules/jest-cli/build/cli/index.js:181:23)
    at Generator.next (<anonymous>:null:null)
    at step (/styles/node_modules/jest-cli/build/cli/index.js:158:191)
    at /styles/node_modules/jest-cli/build/cli/index.js:158:437
    at new Promise (<anonymous>:null:null)
    at Object.<anonymous> (/styles/node_modules/jest-cli/build/cli/index.js:158:99)
    at Object.runCLI (/styles/node_modules/jest-cli/build/cli/index.js:216:18)
    at gulp.task.done (/styles/node_modules/@rubicon/legion-builder/test/sasstrue.js:26:40)
    at taskWrapper (/styles/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:375:14)
    at runBound (domain.js:388:12)
    at asyncRunner (/styles/node_modules/async-done/index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:112:11)
```

**Comment by jgerigmeyer** [comment]
Using the documented jest CLI (e.g. `jest path/to/sasstrue.setup.test.js`), I'm able to run this without issues. So I think the error must be related to your `gulpfile` config and use of the (as far as I can tell undocumented) `jest.runCLI` command. It seems like that command does not make the usual jest globals (e.g. `describe`) available?

Closing as unrelated to True; please correct me if I'm mistaken!

**Comment by chrisopedia** [comment]
@jgerigmeyer can you share with me your set up of how you're running this?

**Comment by jgerigmeyer** [comment]
@chrisopedia Basically, using the CLI works fine:

```sh
jest path/to/sasstrue.setup.test.js
```

The usage of `jest.runCLI` is somewhat undocumented, but the error your seeing seems to stem from importing the entire test-file directly rather than allowing jest to discover and import it. The following gulpfile.js should work:

```js
// gulpfile
'use strict';

const { existsSync, mkdirSync } = require('fs');
const PluginError = require('plugin-error');
const jest = require('jest-cli');

const config = {
        json: true,
        outputFile: 'scss-report.json',
        testMatch: '**/sasstrue.setup.js'
};

gulp.task('test:css', done => jest.runCLI(config, [process.cwd()], results => {
        if (results.numFailedTests || results.numFailedTestSuites) {
            const error = new PluginError('jest-cli', { message: 'Failed at least 1 test' });
            return done(error);
        }
        return done();
}));

gulp.task('test:css').description = 'Sass unit tests. <http://oddbird.net/true/>';
```

**Comment by chrisopedia** [comment]
That got me closer, but now its getting:

```
[10:05:38] Starting 'test:css'...
Determining test suites to run...[10:05:40] 'test:css' errored after 2 s
[10:05:40] TypeError: globs.map is not a function
    at globsToMatcher (styles/node_modules/jest-cli/build/search_source.js:53:26)
    at new SearchSource (styles/node_modules/jest-cli/build/search_source.js:85:18)
    at styles/node_modules/jest-cli/build/run_jest.js:94:20
    at Generator.next (<anonymous>:null:null)
    at step (styles/node_modules/jest-cli/build/run_jest.js:81:191)
    at styles/node_modules/jest-cli/build/run_jest.js:81:437
    at new Promise (<anonymous>:null:null)
    at styles/node_modules/jest-cli/build/run_jest.js:81:99
    at getTestPaths (styles/node_modules/jest-cli/build/run_jest.js:116:17)
    at styles/node_modules/jest-cli/build/run_jest.js:177:31
    at Generator.next (<anonymous>:null:null)
    at step (styles/node_modules/jest-cli/build/run_jest.js:81:191)
    at styles/node_modules/jest-cli/build/run_jest.js:81:437
    at new Promise (<anonymous>:null:null)
    at styles/node_modules/jest-cli/build/run_jest.js:81:99
    at Promise.all.contexts.map (styles/node_modules/jest-cli/build/run_jest.js:183:22)
    at Array.map (<anonymous>:null:null)
    at styles/node_modules/jest-cli/build/run_jest.js:175:52
    at Generator.next (<anonymous>:null:null)
    at step (styles/node_modules/jest-cli/build/run_jest.js:81:191)
    at styles/node_modules/jest-cli/build/run_jest.js:81:437
    at new Promise (<anonymous>:null:null)
    at styles/node_modules/jest-cli/build/run_jest.js:81:99
    at runJest (styles/node_modules/jest-cli/build/run_jest.js:253:18)
    at styles/node_modules/jest-cli/build/cli/index.js:449:66
    at Generator.next (<anonymous>:null:null)
    at step (styles/node_modules/jest-cli/build/cli/index.js:158:191)
    at styles/node_modules/jest-cli/build/cli/index.js:158:437
    at new Promise (<anonymous>:null:null)
    at styles/node_modules/jest-cli/build/cli/index.js:158:99
    at startRun (styles/node_modules/jest-cli/build/cli/index.js:462:23)
    at styles/node_modules/jest-cli/build/cli/index.js:465:18
    at Generator.next (<anonymous>:null:null)
    at step (styles/node_modules/jest-cli/build/cli/index.js:158:191)
    at styles/node_modules/jest-cli/build/cli/index.js:158:437
    at new Promise (<anonymous>:null:null)
    at styles/node_modules/jest-cli/build/cli/index.js:158:99
    at runWithoutWatch (styles/node_modules/jest-cli/build/cli/index.js:469:19)
    at styles/node_modules/jest-cli/build/cli/index.js:415:185
    at Generator.next (<anonymous>:null:null)
    at step (styles/node_modules/jest-cli/build/cli/index.js:158:191)
    at styles/node_modules/jest-cli/build/cli/index.js:158:361
    at <anonymous>:null:null
    at process._tickCallback (internal/process/next_tick.js:118:7)```
