### ISSUE TITLE
Testing output that contains html[dir=

### ISSUE THREAD

**Issue by schalkneethling** [oddbird/true#150]
First off, thank you for this great tool. I am currently writing a test for a `mixin` that outputs something like this:

```
.class {
  float: left;
}
html[dir="rtl"] .class {
  float: right;
}
```

The problem is, when I use the `output`, `expected` form of a test, the expected would be the following:

```
.test-output {
  float: left;
}
.test-output html[dir="rtl"] .test-output {
  float: right;
}
```

Is there a way to prevent the output of the `.test-output` class? I thought of using `@include contains` but this does not work either:

```
@include describe("bidi") {
  @include it("Returns a single LTR style rule with a RTL override") {
    @include assert {
      @include output {
        @include bidi((float, left, right));
      }

      @include contains {
        html[dir="rtl"] .test-output {
          float: right;
        }
      }
    }
  }
}
```

## Test output

```
bidi
    ✕ Returns a single LTR style rule with a RTL override (2ms)

  ● bidi › Returns a single LTR style rule with a RTL override

    assert.(received, expected)

    Expected value   undefined
    Received:
      undefined
    
    Message:
       (".test-output .class {
      float: left;
    }
    
    html[dir="rtl"] .test-output .class {
      float: right;
    }" equal ".test-output html[dir="rtl"] .test-output {
      float: right;
    }")
         + expected - actual
    
         -.test-output .class {
      float: left;
    }
    
    html[dir="rtl"] .test-output .class {
      float: right;
    }
         +.test-output html[dir="rtl"] .test-output {
      float: right;
    }
    

    Difference:

    Compared values have no visual difference.

      at node_modules/sass-true/lib/main.js:84:20
      at arrayEach (node_modules/lodash.foreach/index.js:35:9)
      at forEach (node_modules/lodash.foreach/index.js:290:10)
      at Object.<anonymous> (node_modules/sass-true/lib/main.js:82:9)
```

Thank you in advance for your assistance.

**Comment by schalkneethling** [comment]
Figured it out. The docs actually mention this:

```
$selector: true (bool)

Optionally wrap the contents in a .test-output selector block, so you can test property-value output directly.

```

Changing the test as follows works:

```
@include describe("bidi") {
  @include it("Returns a single LTR style rule with a RTL override") {
    @include assert {
      @include output(false) {
        .expect {
          @include bidi((float, left, right));
        }
      }

      @include expect(false) {
        .expect {
          float: left;
        }
        html[dir="rtl"] .expect {
          float: right;
        }
      }
    }
  }
}
```

**Comment by mirisuzanne** [comment]
🎉 docs! Glad you got it working! 😄
