### ISSUE TITLE
Doesn't work on dart-sass ("sass": "^1.26.5")

### ISSUE THREAD

**Issue by deepak0174** [oddbird/true#164]
Code is working in node-sass but as soon the sass compiler is changed to sass (dart-sass) it shows an error `encountered a Declaration exception`

In short same code won't work if compiler is changed to dart-sass

dart-sass recently added some new features in its latest release, and it is the only implementation available with sass latest module system,

**Comment by mirisuzanne** [comment]
I'm using True (5.0.0) with Dart Sass (1.26.5) without issues, so I'll need a bit more detail to help track this down. Are you using the latest version of True? Is there more detail provided with the error? Can you isolate what code is causing that error?

**Comment by deepak0174** [comment]
Error above occured in monorepo project, But even in normal setting dart-sass doesn't work.
[sass-true-bug-repo](https://github.com/deepak0174/sass-true-dart-bug.git)

```bash
git clone https://github.com/deepak0174/sass-true-dart-bug.git
cd sass-true-dart-bug/
yarn
yarn test
```

This repo will show that same code works on node-sass but fails in dart-sass.

`scss.node-sass.test.js` -> node-sass
`scss.dart-sass.test.js` and `scss.dart-sass-2.test.js` -> dart-sass

```bash
yarn run v1.22.4
$ jest --verbose
 FAIL  __test__/scss.dart-sass-2.test.js
  ● Test suite failed to run

    home/deepak/projects/delete/sass-true-dart-bug/__test__/jumbo2.scss: no such file or directory

      3 | 
      4 | var sassFile = path.join(__dirname, 'jumbo2.scss');
    > 5 | sassTrue.runSass(
        |          ^
      6 |   {
      7 |     file: sassFile,
      8 |   },

      at Object._newRenderError (node_modules/sass/sass.dart.js:13628:19)
      at StaticClosure._renderSync (node_modules/sass/sass.dart.js:13453:18)
      at Object.Primitives_applyFunction (node_modules/sass/sass.dart.js:1064:30)
      at Object.Function_apply (node_modules/sass/sass.dart.js:4895:16)
      at _callDartFunctionFast (node_modules/sass/sass.dart.js:6577:16)
      at Object.renderSync (node_modules/sass/sass.dart.js:6555:18)
      at Object.runSass (node_modules/sass-true/lib/main.js:46:18)
      at Object.<anonymous> (__test__/scss.dart-sass-2.test.js:5:10)

 PASS  __test__/scss.node-sass.test.js
  basic scss setup test
    ✓ Scss test 1 (2 ms)
  basic scss setup test with long sass-true import
    ✓ Scss test 2 (1 ms)

 FAIL  __test__/scss.dart-sass.test.js
  ● Test suite failed to run

    home/deepak/projects/delete/sass-true-dart-bug/__test__/jumbo.scss: no such file or directory

      3 | 
      4 | var sassFile = path.join(__dirname, 'jumbo.scss');
    > 5 | sassTrue.runSass(
        |          ^
      6 |   {
      7 |     file: sassFile,
      8 |   },

      at Object._newRenderError (node_modules/sass/sass.dart.js:13628:19)
      at StaticClosure._renderSync (node_modules/sass/sass.dart.js:13453:18)
      at Object.Primitives_applyFunction (node_modules/sass/sass.dart.js:1064:30)
      at Object.Function_apply (node_modules/sass/sass.dart.js:4895:16)
      at _callDartFunctionFast (node_modules/sass/sass.dart.js:6577:16)
      at Object.renderSync (node_modules/sass/sass.dart.js:6555:18)
      at Object.runSass (node_modules/sass-true/lib/main.js:46:18)
      at Object.<anonymous> (__test__/scss.dart-sass.test.js:5:10)

 PASS  __test__/basic.test.js
  Jest Setup Test
    ✓ Test 1 (2 ms)

Test Suites: 2 failed, 2 passed, 4 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        3.044 s
Ran all test suites.

```

**Comment by deepak0174** [comment]
Error above occur in monorepo project. But still same code won't work on normal package if i change the compiler to dart-sass(sass).
[sass-true-dart-bug](https://github.com/deepak0174/sass-true-dart-bug)

```bash
git clone https://github.com/deepak0174/sass-true-dart-bug
yarn
yarn test
```

`scss.node-sass.test.js` is node-sass setup file

`scss.dart-sass.test.js` and `scss.dart-sass-2.test.js` are dart-sass setup file.


```bash
yarn run v1.22.4
$ jest --verbose
 PASS  __test__/basic.test.js
  Jest Setup Test
    ✓ Test 1 (2 ms)

 PASS  __test__/scss.node-sass.test.js
  basic scss setup test
    ✓ Scss test 1 (1 ms)
  basic scss setup test with long sass-true import
    ✓ Scss test 2

 FAIL  __test__/scss.dart-sass-2.test.js
  ● Test suite failed to run

    home/deepak/projects/delete/sass-true-dart-bug/__test__/jumbo2.scss: no such file or directory

      3 | 
      4 | var sassFile = path.join(__dirname, 'jumbo2.scss');
    > 5 | sassTrue.runSass(
        |          ^
      6 |   {
      7 |     file: sassFile,
      8 |   },

      at Object._newRenderError (node_modules/sass/sass.dart.js:13628:19)
      at StaticClosure._renderSync (node_modules/sass/sass.dart.js:13453:18)
      at Object.Primitives_applyFunction (node_modules/sass/sass.dart.js:1064:30)
      at Object.Function_apply (node_modules/sass/sass.dart.js:4895:16)
      at _callDartFunctionFast (node_modules/sass/sass.dart.js:6577:16)
      at Object.renderSync (node_modules/sass/sass.dart.js:6555:18)
      at Object.runSass (node_modules/sass-true/lib/main.js:46:18)
      at Object.<anonymous> (__test__/scss.dart-sass-2.test.js:5:10)

 FAIL  __test__/scss.dart-sass.test.js
  ● Test suite failed to run

    home/deepak/projects/delete/sass-true-dart-bug/__test__/jumbo.scss: no such file or directory

      3 | 
      4 | var sassFile = path.join(__dirname, 'jumbo.scss');
    > 5 | sassTrue.runSass(
        |          ^
      6 |   {
      7 |     file: sassFile,
      8 |   },

      at Object._newRenderError (node_modules/sass/sass.dart.js:13628:19)
      at StaticClosure._renderSync (node_modules/sass/sass.dart.js:13453:18)
      at Object.Primitives_applyFunction (node_modules/sass/sass.dart.js:1064:30)
      at Object.Function_apply (node_modules/sass/sass.dart.js:4895:16)
      at _callDartFunctionFast (node_modules/sass/sass.dart.js:6577:16)
      at Object.renderSync (node_modules/sass/sass.dart.js:6555:18)
      at Object.runSass (node_modules/sass-true/lib/main.js:46:18)
      at Object.<anonymous> (__test__/scss.dart-sass.test.js:5:10)

Test Suites: 2 failed, 2 passed, 4 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        2.595 s
Ran all test suites.
error Command failed with exit code 1.

```

**Comment by mirisuzanne** [comment]
I can confirm I'm getting the same error from that repo. We'll look into it!

**Comment by jgerigmeyer** [comment]
@deepak0174 This is an error with your Jest configuration.

> The default environment in Jest is a browser-like environment through `jsdom`. If you are building a node service, you can use the `node` option to use a node-like environment instead.

Adding `--env=node` to your `jest` command fixes it.

Cf. https://jestjs.io/docs/en/configuration#testenvironment-string
